 - name: create ec2 instance
     ec2:
        key_name: phani_aws
        region: us-west-2
        group_id: "{{ sg.group_id }}"
        instance_type: t2.micro
        image: ami-01f05461
        wait: yes
        instance_tags:
            Name: monitoring
        count: 1
        vpc_subnet_id: subnet-83ed6ae7
        assign_public_ip: yes
     register: ec2

