---
   - name: download deb pckg from internet
     command: wget https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.0-1479719016beta2_amd64.deb
   
   - name: install libfontconfig
     apt: name=libfontconfig state=present update_cache=yes

   - name: depackage grafana deb file
     apt:
       deb: /home/ubuntu/grafana_4.0.0-1479719016beta2_amd64.deb
 
   - name: restart grafana
     service: name=grafana-server state=restarted
