---
   - name: download deb pckg from internet
     command: wget https://dl.influxdata.com/influxdb/releases/influxdb_1.0.0_amd64.deb

   - name: depackage influx deb file
     apt:
       deb: /home/ubuntu/influxdb_1.0.0_amd64.deb

   - name: restart influx
     service: name=influxdb state=restarted

